image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - command: >
        npm i -g heroku;
        pipenv install;
        psql -U gitpod -c 'CREATE DATABASE breathecode;';
        psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d breathecode;
        pipenv run migrate;
        pipenv run start;