# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: 3.10.5  # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64    # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          prerelease: false     # Allow prerelease versions to be installed
          enable-pep582: true  # Enable PEP 582 package loading globally

      - name: Install dependencies
        run: pdm install       # Then you can use pdm in the following steps.

      - name: Test with pytest
        run: |
          pdm run pcov_ci

      - uses: codecov/codecov-action@v1
        if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/apiv2' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

      - name: Upload coverage data to coveralls.io
        if: ${{ github.event_name == 'pull_request' || github.repository == 'breatheco-de/apiv2' }}
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ github.token }}
